#pragma once

enum DEFAULT_KEYWORD { DEFAULT_KEYWORD_COUNT = 0 };

const char *default_keywords[DEFAULT_KEYWORD_COUNT] = {};

enum C_KEYWORD {
  ALIGNAS = 0,
  ALIGNOF,
  ASSERT,
  AUTO,
  BOOL,
  BREAK,
  CASE,
  CHAR,
  CONST,
  CONSTEXPR,
  CONTINUE,
  DEFAULT,
  DEFINE,
  DO,
  DOUBLE,
  ELSE,
  ENUM,
  EXTERN,
  FALSE,
  FLOAT,
  FOR,
  GOTO,
  IF,
  INCLUDE,
  INLINE,
  INT,
  LONG,
  NULLPTR,
  PRAGMA,
  REGISTER,
  RESTRICT,
  RETURN,
  SHORT,
  SIGNED,
  SIZEOF,
  STATIC,
  STATIC_ASSERT,
  STRUCT,
  SWITCH,
  THREAD_LOCAL,
  TRUE,
  TYPEDEF,
  TYPEOF,
  TYPEOF_UNQUAL,
  UNION,
  UNSIGNED,
  VOID,
  VOLATILE,
  WHILE,
  C_KEYWORD_COUNT
};

const char *c_keywords[C_KEYWORD_COUNT] = {
    "alignas",       "alignof",   "assert",   "auto",
    "bool",          "break",     "case",     "char",
    "const",         "constexpr", "continue", "default",
    "define",        "do",        "double",   "else",
    "enum",          "extern",    "false",    "float",
    "for",           "goto",      "if",       "include",
    "inline",        "int",       "long",     "nullptr",
    "pragma",        "register",  "restrict", "return",
    "short",         "signed",    "sizeof",   "static",
    "static_assert", "struct",    "switch",   "thread_local",
    "true",          "typedef",   "typeof",   "typeof_unqual",
    "union",         "unsigned",  "void",     "volatile",
    "while"};
